# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('icons',           'icons'),
    ],
    hiddenimports=[
        # ── PyQt5 ──────────────────────────────────────────────
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtPrintSupport',
        'PyQt5.sip',
        # ── 네트워크 ────────────────────────────────────────────
        'paramiko',
        'paramiko.transport',
        'paramiko.auth_handler',
        'paramiko.channel',
        'paramiko.packet',
        'paramiko.sftp_client',
        'cryptography',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        # ── 데이터 / 문서 ────────────────────────────────────────
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'pandas',
        'numpy',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_agg',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'reportlab',
        'reportlab.pdfgen',
        'reportlab.lib',
        'docx',
        'docx.oxml',
        # ── UI 모듈 ──────────────────────────────────────────────
        'ui.main_window',
        'ui.network_tab',
        'ui.console_tab',
        'ui.monitoring_tab',
        'ui.dogu_tab',
        'ui.about_tab',
        'ui.home_tab',
        'ui.report_tab',
        'ui.log_analyzer_tab',
        'ui.config_compare_tab',
        'ui.inspection_tab',
        'ui.file_viewer_tab',
        'ui.theme',
        'ui.license_dialog',
        'ui.disclaimer_dialog',
        'ui.onboarding_dialog',
        'ui.premium_popup',
        # ── Core 모듈 ─────────────────────────────────────────────
        'core.workers',
        'core.license_manager',
        'core.config_diff',
        'core.parsers',
        'core.inspection_parser',
        'core.i18n',
        'core.updater',
        'core.log_analyzer',
        'core.log_analyzer.parser',
        'core.log_analyzer.constants',
        # ── 시리얼 ────────────────────────────────────────────────
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'doctest',
        '_pytest',
        'pytest',
        'scipy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NetworkAutomation',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icons/app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='NetworkAutomation',
)
